### PR TITLE
Allow specifying modpack by version

### PR DESCRIPTION
**Pull request by boatrite**
I needed this functionality the other day, so I wrote it. I made an attempt to follow the current style. Please let me know what you would like changed, or feel free to close if you don't like the functionality.

2016-12-04-130738_796x621_scrot

Cheers

### CODE REVIEW

**Comment by Nincodedo** [comment]
For the version ID, is it the file ID or the actual version number of the modpack?

**Comment by boatrite** [comment]
It is the file id. It is what appears in the curse download url. e.g. Given this url https://minecraft.curseforge.com/projects/all-the-mods/files/2348158/download, the Curse Version ID is 2348158

**Comment by Nincodedo** [comment]
OK. Should the text say Curse file ID then? I think that's more accurate.

**Comment by boatrite** [comment]
@Nincodedo Fixed. @Vazkii any thoughts?

**Comment by brodycas3** [comment]
omg yes. Please add this

**Pull request merged**
