### PR TITLE
URL Encoding Problems

### LINKED ISSUE #45: doubled HTML encoding
The problem is most likely in getLocationHeader().

modpack URL: https://minecraft.curseforge.com/projects/age-of-engineering
log:
File download URL is https://minecraft.curseforge.com/projects/better-builders-wands/files/2394395/download
Downloading BetterBuildersWands-1.10.2-0.11.1.220%2Bf8232fe.jar
Error: class java.io.IOException: Server returned HTTP response code: 403 for URL: https://media.forgecdn.net/files/2394/395/BetterBuildersWands-1.10.2-0.11.1.220%252Bf8232fe.jar

The "%252B" here should be "%2B".

tentative variable backtrace:
CMPDL.java:
 315:log("Downloading " + filename); //filename = ...%2B...jar this should be '+'
 306:filename = URLDecoder.decode(filename, "UTF-8"); //filename = ...%2B...jar this should be '+'
 305:String filename = m.group(1); //filename = ...%252B...jar this should be "%2B"
 301:Matcher m = FILE_NAME_URL_PATTERN.matcher(finalUrl);
 300:String finalUrl = getLocationHeader(fileDlUrl);
 298:log("File download URL is " + fileDlUrl); //fileDlUrl = https://minecraft.curseforge.com/projects/better-builders-wands/files/2394395/download

### PR DESCRIPTION
**Pull request by zachdeibert**
This fixes issue #45 .

### CODE REVIEW

**Comment by zachdeibert** [comment]
This also fixes #41, #37, #35, and #34 .

**Comment by zachdeibert** [comment]
Actually, spaces in the URLs are still broken.

**Comment by zachdeibert** [comment]
There we go, now it works. :)

**Comment by tomKPZ** [comment]
@Vazkii any chance we can get this merged?  Most modpacks fail to download because of this issue.

**Comment by MrLavender** [comment]
This does not fix the issue. There are still some mods that fail due to encoding (try downloading any pack that contains Better Builder's Wands, like Sevtech Ages).

The root problem is that encoding is being forced when it shouldn't be, and there is an easier way to solve that. The URI(String) constructor does not encode and will throw a URISyntaxException if the string isn't valid, so just try that first then only encode if it fails. [See here](https://github.com/MrLavender/CMPDL/commit/cf22fb7af8eb6b14c8848f69993e09539e2fdd48).

I would submit a pull request but there doesn't seem to be much activity here lately...

So, in case it's useful to anyone, I have uploaded a fat jar build containing this fix [here](https://github.com/MrLavender/CMPDL/releases/tag/1.1.4-SNAPSHOT).

**Pull request merged**
